#! /bin/bash
echo Welcome to the LAMP installer.
read -r -p 'enter sudo password: ' supwd # prompt user for sudo password
echo installing LAMP..
echo stand by...
echo $supwd | sudo -S apt-get update
echo Grabbing updates...
echo Please stand by...
echo $supwd | sudo -S apt-get -y install apache2
echo Installing Apache....
echo Stand by...
echo $supwd | sudo -S apt-get -y install curl
echo Installing Curl....
echo Stand by...
echo $supwd | sudo -S apt-get -y install php7
echo Installing PHP....
echo Stand by...
echo $supwd | sudo -S apt-get -y install mysql-server
echo Installing SQL....
echo Stand by...